import logging
import json
from app.config import settings
from app.services.mock_service import MockService
from app.services.java_service import JavaService
from app.models import Lead, LeadCreateRequest, LeadCreateResponse, LeadListResponse, ToolResult

def get_service(token: str = None):
    if settings.USE_MOCK_DATA:
        return MockService(token)
    return JavaService(token)

def format_whatsapp_lead_create(result: LeadCreateResponse) -> str:
    """Format lead creation for WhatsApp."""
    message = (
        f"🆕 *New Lead Captured!*\n\n"
        f"👤 *Name:* {result.custName}\n"
        f"📞 *Phone:* {result.phone}\n"
        f"📝 *Enquiry For:* {result.enqFor}\n"
        f"💰 *Potential Value:* ₹{result.leadValue:,.2f}\n"
        f"📍 *Status:* {result.status}\n\n"
        f"Go to QTick to manage this lead! 🚀"
    )
    return json.dumps(message, ensure_ascii=True)[1:-1]

def format_whatsapp_lead_list(data: LeadListResponse, business_id: int) -> str:
    """Format lead list for WhatsApp."""
    lead_count = len(data.items)
    total_value = sum(item.leadValue for item in data.items)
    
    # Sort leads by value descending for the top 5 list
    sorted_items = sorted(data.items, key=lambda x: x.leadValue, reverse=True)
    
    message = f"📋 *Lead List for Biz #{business_id}*\n"
    message += f"👥 Total Leads: {data.total}\n"
    message += f"💰 Total Potential Value: ₹{total_value:,.2f}\n"
    
    message += "🔝 *Top 5 Leads by Value:*\n"
    # List top 5 leads
    for i, item in enumerate(sorted_items[:5]):
        message += f"{i+1}. *{item.name}* (₹{item.leadValue:,.2f}) - {item.status}\n"
    
    if lead_count > 5:
        message += f"\n...and {lead_count - 5} more."
    
    message += "\n\nGenerated by QTick AI 🤖"
    return json.dumps(message, ensure_ascii=True)[1:-1]

async def create_lead(
    name: str, 
    business_id: int,
    email: str = None, 
    phone: str = None,
    source: str = "manual",
    notes: str = None,
    location: str = None,
    enquiry_for: str = None,
    details: str = None,
    interest: int = None,
    follow_up_date: str = None,
    enquired_on: str = None,
    enquiry_for_time: str = None,
    attention_staff_id: int = None,
    attention_channel: str = None,
    third_status: str = None,
    service_name: str = None,
    prompt: str = None,
    token: str = None
) -> ToolResult:
    """Create a new lead."""
    service = get_service(token)
    
    # If enquiry_for is not provided, use service_name, then original chat message (prompt)
    if not enquiry_for:
        if service_name:
            enquiry_for = service_name
        elif prompt:
            enquiry_for = prompt
        
    request = LeadCreateRequest(
        business_id=int(business_id),
        name=name,
        email=email,
        phone=phone,
        source=source,
        notes=notes,
        location=location,
        enquiry_for=enquiry_for,
        details=details,
        interest=interest,
        follow_up_date=follow_up_date,
        enquired_on=enquired_on,
        enquiry_for_time=enquiry_for_time,
        attention_staff_id=attention_staff_id,
        attention_channel=attention_channel,
        third_status=third_status,
        service_name=service_name
    )
    result = await service.create_lead(request)
    logging.info(result)    
    
    whatsAppText = format_whatsapp_lead_create(result)
    
    return ToolResult(
        type="create_lead",
        data=result,
        text=f"Lead created successfully. ID: {result.lead_id}, Customer: {result.custName}, Phone: {result.phone}, Enquiry For: {result.enqFor}, Value: {result.leadValue}, Status: {result.status}",
        whatsAppText=whatsAppText
    )

async def list_leads(business_id: int, token: str = None) -> ToolResult:
    """List all leads."""
    print(token)
    service = get_service(token)

    data = await service.list_leads(int(business_id))
    
    # Generate text response
    total_value = sum(item.leadValue for item in data.items)
    summary = f"👥 {data.total} leads found for business {business_id}. 💰 Total Potential Value: ₹{total_value:,.2f}"
    
    # Generate Markdown table
    if data.items:
        table = "| Lead ID | Name | Status | Created At | Phone | Email | Source | Value |\n"
        table += "|---|---|---|---|---|---|---|---|\n"
        for item in data.items:
            table += f"| {item.lead_id} | {item.name} | {item.status} | {item.created_at} | {item.phone} | {item.email} | {item.source} | {item.leadValue} |\n"
        text = f"{summary}\n\n{table}"
    else:
        text = summary
        
    whatsAppText = format_whatsapp_lead_list(data, business_id)

    return ToolResult(
        type="list_leads", 
        data=data.items, 
        text=text,
        whatsAppText=whatsAppText
    )
